apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aam-wp-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - host: aam-wp.dsam.web.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aam-wp-service
                port:
                  number: 80