apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=        # base64 dari "password"
  mysql-database: d29yZHByZXNz             # base64 dari "wordpress"
  mysql-user: dXNlcm5hbWU=                 # base64 dari "username"
  mysql-password: cGFzc3dvcmQ=             # base64 dari "password"
