apiVersion: apps/v1
kind: Deployment
metadata:
  name: aam-wp-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aam-wp-deployment
  template:
    metadata:
      labels:
        app: aam-wp-deployment
    spec:
      containers:
      - name: aam-wp-container
        image: aamdsam/wordpress-aam:latest
        ports:
          - containerPort: 80
          - containerPort: 443
        env:
          - name: WORDPRESS_DB_HOST
            value: "aam-mysql-service.default.svc.cluster.local"
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: aam-mysql-secret
                key: mysql-user
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aam-mysql-secret
                key: mysql-password
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: aam-mysql-secret
                key: mysql-database
        volumeMounts:
          - name: wordpress-data
            mountPath: /var/www/html
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: 1
            memory: "512Mi"
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: aam-wp-pvc