apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: aamdsam/wordpress-aam:latest
        ports:
          - containerPort: 80
          - containerPort: 443
        env:
          - name: WORDPRESS_DB_HOST
            value: "mysql.wordpress.svc.cluster.local"
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-user
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-password
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-database
                key: mysql-database
        volumeMounts:
          - name: wordpress-data
            mountPath: /var/www/html
        resources:
          limits:
            cpu: "1500m"
            memory: "512Mi"
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc
